// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package services

import (
	"blog-users/api/protos/user"
	"blog-users/internal/app/user/repositories"
	"blog-users/internal/pkg/config"
	"blog-users/internal/pkg/database"
	"blog-users/internal/pkg/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateUserService(cf string, rpo repositories.UserRepository, userclient bloguser.UserClient) (UserService, error) {
	viper, err := config.New(cf)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	userService := NewUserService(logger, viper, rpo, userclient)
	return userService, nil
}

// wire.go:

var testProviderSet = wire.NewSet(log.ProviderSet, config.ProviderSet, database.ProviderSet, ProviderSet)
